import { readFileSync, readdirSync } from "node:fs";
import { buildSchema, isEnumType, isInputObjectType, isInterfaceType, isObjectType, isUnionType, validateSchema, type GraphQLField, type GraphQLInputField } from "graphql";
import { describe, expect, it } from "vitest";
import { bookstoreSchemaText } from "../../../examples/bookstore-ts/src/index.ts";
import { generateGraphql, loadSchema, type TypeRef } from "./index.ts";

const BOOKSHOP = readFileSync(new URL("../../../examples/typescript/src/bookshop.rayfold", import.meta.url), "utf8");

const PETS = `
"""Something with a name."""
object Named @interface { name: String }
entity Cat implements Named { id: ID name: String lives: Int }
entity Dog implements Named {
  id: ID
  name: String
  nickname: String? @deprecated(reason: "Renamed", sunset: "2027-01-01", replacement: "name")
  friends(page: PageArgs = { first: 5 }, size: Size = SMALL): Page<Dog>
}
object Photo { url: String width: Int? }
union Pet = Cat | Dog
enum Size { SMALL LARGE @deprecated(reason: "Too big") }
scalar Email @format("email")
error Gone { since: Instant }
event Adopted { petId: ID contact: Email }
input PetFilter { size: Size = LARGE names: [String]? since: Date? }
view Dog.card = { id name }
query pets(filter: PetFilter?, page: PageArgs = { first: 10 }): Page<Pet>
query media(tags: [String] = ["cute"]): [Photo]
command adoptPet(petId: ID, note: String? @deprecated(reason: "Unused")): Pet throws Gone emits Adopted
stream feed: Adopted
`;

const fixtures = new URL("../../../conformance/fixtures/core/", import.meta.url);
const SCHEMAS: Array<[string, string]> = [
  ["bookshop", BOOKSHOP],
  ["bookstore", bookstoreSchemaText()],
  ["pets", PETS],
  ...readdirSync(fixtures)
    .sort()
    .map((f): [string, string] => [f, (JSON.parse(readFileSync(new URL(f, fixtures), "utf8")) as { schema: string }).schema]),
];

describe("rayfold gen graphql", () => {
  it("prints the bookshop as GraphQL SDL, and lists what GraphQL cannot say", () => {
    const { sdl, lost } = generateGraphql(loadSchema(BOOKSHOP).ir);
    expect(sdl).toBe(`# Generated by \`rayfold gen graphql\`. Do not edit.

type Query {
  book(id: ID!): Book
  books(page: PageArgs! = { first: 20 }): BookPage
}

type Mutation {
  """Take copies off the shelf. Fails if there are not enough."""
  buy(bookId: ID!, qty: Int! = 1): Book
  restock(bookId: ID!, qty: Int!): Book
}

type Author {
  id: ID!
  name: String!
}

type Book {
  id: ID!
  title: String!
  stock: Int!
  author: Author!
  """What the shop paid. Only staff can see it."""
  costPrice: Decimal
}

type OutOfStock {
  bookId: ID!
  available: Int!
}

type StockChanged {
  bookId: ID!
  stock: Int!
}

type BookPage {
  items: [Book!]!
  cursor: String
  hasMore: Boolean!
  total: Int
}

input PageArgs {
  first: Int! = 20
  after: String
  offset: Int
}

scalar Decimal @specifiedBy(url: "https://rayfold.dev/spec/01-schema")
`);
    expect(lost).toEqual([
      "Each operation succeeds or fails on its own. GraphQL can only show that with nullable fields, so every Query and Mutation field is nullable.",
      "Queries: live: true, reads cached by GET or QUERY with an ETag, and the default view a call without a shape gets.",
      "Commands: the idempotency key each call carries, and the cache patches each one returns.",
      "Batches: several operations in one request, where a later one can use an earlier one's result ($ref).",
      "buy() throws OutOfStock: GraphQL has no typed errors, so the SDL has the type but not that buy() throws it.",
      "StockChanged is emitted by buy() and restock(): GraphQL has no events besides subscriptions.",
      "@allow (buy(), restock(), Book.costPrice): access rules, which the server still enforces.",
      "@cache (Book): HTTP cache lifetimes.",
      "@range (buy(qty), restock(qty)): allowed ranges.",
    ]);
  });

  it("carries interfaces, unions, enums, inputs, field arguments, streams and deprecations across", () => {
    const { sdl, lost } = generateGraphql(loadSchema(PETS).ir);
    const lines = sdl.split("\n");
    for (const line of [
      "interface Named {",
      "type Cat implements Named {",
      '  nickname: String @deprecated(reason: "Renamed. Use name instead. Removed after 2027-01-01.")',
      "  friends(page: PageArgs! = { first: 5 }, size: Size! = SMALL): DogPage!",
      "union Pet = Cat | Dog",
      '  LARGE @deprecated(reason: "Too big")',
      "scalar Email",
      "  size: Size! = LARGE",
      "  names: [String!]",
      "  pets(filter: PetFilter, page: PageArgs! = { first: 10 }): PetPage",
      '  media(tags: [String!]! = ["cute"]): [Photo!]',
      '  adoptPet(petId: ID!, note: String @deprecated(reason: "Unused")): Pet',
      "type Subscription {",
      "  feed: Adopted",
      'scalar Date @specifiedBy(url: "https://rayfold.dev/spec/01-schema")',
      'scalar Instant @specifiedBy(url: "https://rayfold.dev/spec/01-schema")',
    ]) {
      expect(lines, line).toContain(line);
    }
    // guard: only the scalars the schema uses are declared
    expect(sdl).not.toContain("scalar Long");
    expect(lost).toContain("Each operation succeeds or fails on its own. GraphQL can only show that with nullable fields, so every Query, Mutation and Subscription field is nullable.");
    expect(lost).toContain("Views (Dog.card): a GraphQL schema has no named selections; the nearest thing is a fragment in client code.");
    expect(lost).toContain("adoptPet() throws Gone: GraphQL has no typed errors, so the SDL has the type but not that adoptPet() throws it.");
    expect(lost).toContain("Adopted is emitted by adoptPet(): GraphQL has no events besides subscriptions.");
    expect(lost).toContain("@format (Email): value formats.");
    // every deprecation here sits where GraphQL allows one, so none is reported lost
    expect(lost.filter((l) => l.startsWith("@deprecated"))).toEqual([]);
  });

  it("reports a deprecation GraphQL cannot hold, on a whole type or a required argument, instead of writing invalid SDL", () => {
    const schema = `entity Cat @deprecated(reason: "Gone") { id: ID } query cat(id: ID @deprecated(reason: "Old")): Cat`;
    const { sdl, lost } = generateGraphql(loadSchema(schema).ir);
    expect(sdl).toContain("  cat(id: ID!): Cat\n");
    expect(sdl).toContain("type Cat {\n");
    expect(lost).toContain("@deprecated (cat(id), Cat): deprecations GraphQL only allows on fields, optional arguments and enum values.");
    expect(validateSchema(buildSchema(sdl))).toEqual([]);
  });

  it("gives a schema with no query the Query field GraphQL requires, and says so", () => {
    const { sdl, lost } = generateGraphql(loadSchema(`entity Note { id: ID } command write(text: String): Note`).ir);
    expect(sdl).toContain('type Query {\n  """This schema declares no query, and GraphQL needs a field here."""\n  _: Boolean\n}');
    expect(lost).toContain("The schema declares no query, so Query holds the placeholder field _ that GraphQL requires.");
    expect(validateSchema(buildSchema(sdl))).toEqual([]);
  });

  it("gives a type or input with no fields the field GraphQL requires, and says so (guard - a type with fields gets none)", () => {
    const src = `error NotFound {} object Empty {} input NoFilter {} object Tag { name: String } entity Book { id: ID tag: Tag e: Empty } query book(id: ID, f: NoFilter?): Book throws NotFound`;
    const { sdl, lost } = generateGraphql(loadSchema(src).ir);
    expect(sdl).toContain('type NotFound {\n  """NotFound has no fields in the Rayfold schema, and GraphQL needs one here."""\n  _: Boolean\n}');
    expect(sdl).toContain('input NoFilter {\n  """NoFilter has no fields in the Rayfold schema, and GraphQL needs one here."""\n  _: Boolean\n}');
    expect(sdl).toContain("type Tag {\n  name: String!\n}");
    expect(lost).toContain("NotFound, Empty and NoFilter have no fields, and GraphQL allows no type without one, so each holds the placeholder field _.");
    expect(validateSchema(buildSchema(sdl))).toEqual([]);
    expect(generateGraphql(loadSchema(`object Tag { name: String } query t: Tag`).ir).lost.some((l) => l.includes("placeholder field _."))).toBe(false);
  });

  it("refuses a schema whose own type takes the name of a GraphQL root type", () => {
    expect(() => generateGraphql(loadSchema(`entity Query { id: ID } query q: Query`).ir)).toThrow("Query is a type in this schema, and GraphQL needs that name for the query root type");
    // guard: the same name is fine for a root GraphQL does not need here
    expect(() => generateGraphql(loadSchema(`entity Mutation { id: ID } query q: Mutation`).ir)).not.toThrow();
  });

  it("every schema in the repository becomes a valid GraphQL schema with each operation, type and field in place", () => {
    /** The GraphQL type a Rayfold type becomes: nullability flipped, Page<T> named after T, root fields nullable. */
    const expected = (t: TypeRef, root = false): string => {
      const inner = t.kind === "list" ? `[${expected(t.of)}]` : t.name === "Page" && t.args?.[0]?.kind === "named" ? `${t.args[0].name}Page` : t.name;
      return t.nullable || root ? inner : `${inner}!`;
    };
    for (const [name, text] of SCHEMAS) {
      const { ir } = loadSchema(text);
      const schema = buildSchema(generateGraphql(ir).sdl);
      expect(validateSchema(schema), name).toEqual([]);
      const roots = { query: schema.getQueryType(), command: schema.getMutationType(), stream: schema.getSubscriptionType() };
      for (const op of Object.values(ir.ops)) {
        const field = roots[op.kind]?.getFields()[op.name];
        expect(field, `${name}: ${op.name}`).toBeDefined();
        expect([String(field!.type), field!.args.map((a) => `${a.name}: ${String(a.type)}`)], `${name}: ${op.name}`).toEqual([expected(op.returns, true), op.args.map((a) => `${a.name}: ${expected(a.type)}`)]);
      }
      for (const t of Object.values(ir.types)) {
        if (t.builtin) continue;
        const g = schema.getType(t.name);
        expect(g, `${name}: ${t.name}`).toBeDefined();
        if (t.kind === "enum") {
          expect(isEnumType(g), `${name}: ${t.name}`).toBe(true);
          if (isEnumType(g)) expect(g.getValues().map((v) => v.name), `${name}: ${t.name}`).toEqual(t.values.map((v) => v.name));
        }
        if (t.kind === "union") {
          expect(isUnionType(g), `${name}: ${t.name}`).toBe(true);
          if (isUnionType(g)) expect(g.getTypes().map((m) => m.name), `${name}: ${t.name}`).toEqual(t.members);
        }
        if (!("fields" in t)) continue;
        expect(isObjectType(g) || isInterfaceType(g) || isInputObjectType(g), `${name}: ${t.name}`).toBe(true);
        if (!isObjectType(g) && !isInterfaceType(g) && !isInputObjectType(g)) continue;
        const gFields: Array<GraphQLField<unknown, unknown> | GraphQLInputField> = Object.values(g.getFields());
        expect(gFields.map((f) => `${f.name}: ${String(f.type)}`), `${name}: ${t.name}`).toEqual(t.fields.map((f) => `${f.name}: ${expected(f.type)}`));
        if (t.kind === "entity") {
          expect(isObjectType(g), `${name}: ${t.name}`).toBe(true);
          if (isObjectType(g)) expect(g.getInterfaces().map((i) => i.name), `${name}: ${t.name}`).toEqual(t.implements);
        }
      }
    }
  });
});
