/**
 * Java generation from the IR (`rayfold gen java`): one file holding records for entities, objects, inputs, errors
 * and events, enums, the Page record, marker interfaces for unions, and the operation names with argument records.
 * Plain Java 17 with no library annotations: Jackson and similar libraries map records by component name.
 */
import type { FieldDef, RayfoldSchemaIR, TypeRef } from "./ir.ts";

const SCALARS: Record<string, string> = {
  ID: "String",
  String: "String",
  Int: "Integer",
  Long: "Long",
  Float: "Double",
  Boolean: "Boolean",
  Decimal: "String",
  Instant: "String",
  Date: "String",
  Duration: "String",
  Bytes: "String",
  JSON: "Object",
};

const JAVA_KEYWORDS = new Set([
  "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const", "continue", "default", "do", "double",
  "else", "enum", "extends", "final", "finally", "float", "for", "goto", "if", "implements", "import", "instanceof", "int", "interface",
  "long", "native", "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp", "super", "switch",
  "synchronized", "this", "throw", "throws", "transient", "try", "void", "volatile", "while", "true", "false", "null", "var", "yield",
  "record", "sealed", "permits", "_",
]);

/** A Java identifier for a schema name: keywords get a trailing underscore (`class` becomes `class_`). */
const ident = (name: string): string => (JAVA_KEYWORDS.has(name) ? `${name}_` : name);

/** placeOrder -> PLACE_ORDER */
const constant = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();

const cap = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);

export function generateJava(ir: RayfoldSchemaIR, opts: { pkg?: string; className?: string } = {}): string {
  const pkg = opts.pkg ?? "dev.rayfold.generated";
  const cls = opts.className ?? "RayfoldSchema";
  const types = Object.values(ir.types).filter((t) => !t.builtin);

  // union members carry `$type`, which is how a reader (and the server) tells the members apart
  const unionsOf = new Map<string, string[]>();
  for (const t of types) if (t.kind === "union") for (const m of t.members) unionsOf.set(m, [...(unionsOf.get(m) ?? []), t.name]);

  const java = (t: TypeRef): string => {
    if (t.kind === "list") return `java.util.List<${java(t.of)}>`;
    if (t.name === "Page" && t.args?.[0]) return `Page<${java(t.args[0])}>`;
    const def = ir.types[t.name];
    if (!def) return "Object";
    if (def.kind === "scalar") return SCALARS[t.name] ?? "String";
    return t.name;
  };

  const doc = (lines: string[], indent: string): string[] => {
    const text = lines.filter((l) => l.length).map((l) => l.replace(/\*\//g, "* /"));
    if (!text.length) return [];
    if (text.length === 1 && !text[0]!.includes("\n")) return [`${indent}/** ${text[0]} */`];
    return [`${indent}/**`, ...text.flatMap((l) => l.split("\n")).map((l) => `${indent} * ${l}`.trimEnd()), `${indent} */`];
  };
  const fieldDocs = (fs: FieldDef[]): string[] => fs.filter((f) => f.description).map((f) => `@param ${ident(f.name)} ${f.description!.replace(/\n/g, " ")}`);
  const components = (fs: FieldDef[]): string[] => fs.map((f) => `${java(f.type)} ${ident(f.name)}`);

  const out: string[] = [
    "/* Generated by `rayfold gen java`. Do not edit. */",
    `package ${pkg};`,
    "",
    "/**",
    " * The types and operations of a Rayfold schema. Fields a request did not select, and null values, read as null.",
    ...(types.some((t) => t.kind === "scalar") ? [` * Custom scalars travel as String: ${types.filter((t) => t.kind === "scalar").map((t) => t.name).join(", ")}.`] : []),
    " */",
    `public final class ${cls} {`,
    `    private ${cls}() {}`,
    "",
    "    /** One page of a list: `cursor` asks for the next page while `hasMore` is true. */",
    "    public record Page<T>(java.util.List<T> items, String cursor, Boolean hasMore, Integer total) {}",
    "",
    "    /** Paging arguments: how many items, and where to continue. */",
    "    public record PageArgs(Integer first, String after, Integer offset) {}",
    "",
  ];

  for (const t of types) {
    switch (t.kind) {
      case "entity":
      case "object":
      case "input":
      case "error":
      case "event": {
        const unions = unionsOf.get(t.name) ?? [];
        const comps = components(t.fields);
        out.push(...doc([t.description ?? "", ...fieldDocs(t.fields)], "    "));
        if (unions.length) {
          const args = t.fields.map((f) => ident(f.name));
          out.push(
            `    public record ${t.name}(${["String $type", ...comps].join(", ")}) implements ${unions.join(", ")} {`,
            `        /** A ${t.name} with \`$type\` set, as members of ${unions.join(" and ")} need. */`,
            `        public ${t.name}(${comps.join(", ")}) {`,
            `            this(${[`"${t.name}"`, ...args].join(", ")});`,
            "        }",
            "    }",
          );
        } else out.push(`    public record ${t.name}(${comps.join(", ")}) {}`);
        break;
      }
      case "enum":
        out.push(...doc([t.description ?? ""], "    "));
        out.push(`    public enum ${t.name} { ${t.values.map((v) => ident(v.name)).join(", ")} }`);
        break;
      case "union":
        out.push(...doc([t.description ?? "", `One of ${t.members.join(", ")}; the \`$type\` member says which.`], "    "));
        out.push(`    public interface ${t.name} {}`);
        break;
      case "scalar":
        continue;
    }
    out.push("");
  }

  out.push("    /** Operation names, and a record for the arguments of each operation that takes any. */", "    public static final class Ops {", "        private Ops() {}", "");
  for (const op of Object.values(ir.ops)) {
    out.push(...doc([op.description ?? `The ${op.kind} ${op.name}.`], "        "));
    out.push(`        public static final String ${constant(op.name)} = "${op.name}";`);
    if (op.args.length) out.push(`        public record ${cap(op.name)}Args(${op.args.map((a) => `${java(a.type)} ${ident(a.name)}`).join(", ")}) {}`);
    out.push("");
  }
  out.push("    }", "}");
  return out.join("\n") + "\n";
}
