import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { bookstoreSchemaText } from "../../../examples/bookstore-ts/src/index.ts";
import { generateJava, loadSchema } from "./index.ts";

// The generated Java is compiled with javac and run, when a JDK is on PATH. CI sets REQUIRE_JAVAC=1 so a missing JDK
// fails the run there instead of skipping these tests.
const javac = (() => {
  try {
    execFileSync("javac", ["-version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
})();
if (!javac && process.env["REQUIRE_JAVAC"]) throw new Error("REQUIRE_JAVAC is set but javac is not on PATH");

// a cold javac or java start takes seconds on a busy runner; a hung one is killed at this bound instead of stalling the run
const JDK_MS = 40_000;
const work = mkdtempSync(join(tmpdir(), "rayfold-gen-java-"));
afterAll(() => rmSync(work, { recursive: true, force: true }));

/** Compiles `sources` (path -> text) into `<dir>/out` with javac; returns the class output folder. */
function compile(name: string, sources: Record<string, string>): string {
  const dir = join(work, name);
  const files = Object.entries(sources).map(([path, text]) => {
    const file = join(dir, path);
    mkdirSync(join(file, ".."), { recursive: true });
    writeFileSync(file, text);
    return file;
  });
  execFileSync("javac", ["-Xlint:all", "-Werror", "-d", join(dir, "out"), ...files], { stdio: "pipe", timeout: JDK_MS });
  return join(dir, "out");
}

const PETS = `
"""Something with a name."""
object Named @interface { name: String }
entity Cat implements Named { id: ID name: String lives: Int }
"""
A dog.
Two lines of description.
"""
entity Dog implements Named {
  id: ID
  name: String
  """Java keyword as a field name."""
  class: String
  default: Boolean?
}
object Photo { url: String width: Int? }
union Pet = Cat | Dog
union Media = Photo | Cat
enum Size { SMALL LARGE }
scalar Email
error Gone { since: Instant }
event Adopted { petId: ID contact: Email }
input PetFilter { size: Size? names: [String]? }
query pets(filter: PetFilter?, page: PageArgs = { first: 10 }): Page<Pet>
query media: [Media]
command adoptPet(petId: ID): Pet throws Gone emits Adopted
stream feed: Adopted
`;

const SMALL_PETS = `
"""Something with a name."""
object Named @interface { name: String }
entity Cat implements Named { id: ID name: String lives: Int }
entity Dog implements Named { id: ID name: String class: String default: Boolean? }
object Photo { url: String width: Int? tags: [String?] }
union Pet = Cat | Dog
union Media = Photo | Cat
enum Size { SMALL LARGE }
scalar Email
error Gone { since: Instant }
event Adopted { petId: ID contact: Email }
input PetFilter { size: Size? names: [String]? }
query pets(filter: PetFilter?, page: PageArgs = { first: 10 }): Page<Pet>
command adoptPet(petId: ID): Pet throws Gone emits Adopted
stream feed: Adopted
`;

/** The whole of what `rayfold gen java` writes for SMALL_PETS, line for line. */
const SMALL_PETS_JAVA = [
  "/* Generated by `rayfold gen java`. Do not edit. */",
  "package demo;",
  "",
  "/**",
  " * The types and operations of a Rayfold schema. Fields a request did not select, and null values, read as null.",
  " * Custom scalars travel as String: Email.",
  " */",
  "public final class Api {",
  "    private Api() {}",
  "",
  "    /** One page of a list: `cursor` asks for the next page while `hasMore` is true. */",
  "    public record Page<T>(java.util.List<T> items, String cursor, Boolean hasMore, Integer total) {}",
  "",
  "    /** Paging arguments: how many items, and where to continue. */",
  "    public record PageArgs(Integer first, String after, Integer offset) {}",
  "",
  "    /** Something with a name. */",
  "    public record Named(String name) {}",
  "",
  "    public record Cat(String $type, String id, String name, Integer lives) implements Pet, Media {",
  "        /** A Cat with `$type` set, as members of Pet and Media need. */",
  "        public Cat(String id, String name, Integer lives) {",
  "            this(\"Cat\", id, name, lives);",
  "        }",
  "    }",
  "",
  "    public record Dog(String $type, String id, String name, String class_, Boolean default_) implements Pet {",
  "        /** A Dog with `$type` set, as members of Pet need. */",
  "        public Dog(String id, String name, String class_, Boolean default_) {",
  "            this(\"Dog\", id, name, class_, default_);",
  "        }",
  "    }",
  "",
  "    public record Photo(String $type, String url, Integer width, java.util.List<String> tags) implements Media {",
  "        /** A Photo with `$type` set, as members of Media need. */",
  "        public Photo(String url, Integer width, java.util.List<String> tags) {",
  "            this(\"Photo\", url, width, tags);",
  "        }",
  "    }",
  "",
  "    /** One of Cat, Dog; the `$type` member says which. */",
  "    public interface Pet {}",
  "",
  "    /** One of Photo, Cat; the `$type` member says which. */",
  "    public interface Media {}",
  "",
  "    public enum Size { SMALL, LARGE }",
  "",
  "    public record Gone(String since) {}",
  "",
  "    public record Adopted(String petId, String contact) {}",
  "",
  "    public record PetFilter(Size size, java.util.List<String> names) {}",
  "",
  "    /** Operation names, and a record for the arguments of each operation that takes any. */",
  "    public static final class Ops {",
  "        private Ops() {}",
  "",
  "        /** The query pets. */",
  "        public static final String PETS = \"pets\";",
  "        public record PetsArgs(PetFilter filter, PageArgs page) {}",
  "",
  "        /** The command adoptPet. */",
  "        public static final String ADOPT_PET = \"adoptPet\";",
  "        public record AdoptPetArgs(String petId) {}",
  "",
  "        /** The stream feed. */",
  "        public static final String FEED = \"feed\";",
  "",
  "    }",
  "}",
  "",
].join("\n");

describe("rayfold gen java", { timeout: 2 * JDK_MS + 5_000 }, () => {
  it("writes one class with records, enums, Page and the operations of the bookstore", () => {
    const src = generateJava(loadSchema(bookstoreSchemaText()).ir, { pkg: "shop.api", className: "Bookstore" });
    expect(src).toContain("package shop.api;");
    expect(src).toContain("public final class Bookstore {");
    expect(src).toContain("public record Book(String id, String title, Format format, String price, Integer stock, Author author, Page<Review> reviews, String costPrice, String ownerId) {}");
    expect(src).toContain("public enum Format { HARDCOVER, PAPERBACK, EBOOK }");
    expect(src).toContain('public static final String PLACE_ORDER = "placeOrder";');
    expect(src).toContain("public record PlaceOrderArgs(OrderInput input) {}");
    // descriptions become Javadoc, field descriptions @param tags
    expect(src).toMatch(/@param price Unit price in the store currency\./);
  });

  it("writes exactly this for a schema with every kind of type: lists, Page, unions, keywords, scalars and argument records", () => {
    expect(generateJava(loadSchema(SMALL_PETS).ir, { pkg: "demo", className: "Api" })).toBe(SMALL_PETS_JAVA);
  });

  it.runIf(javac)("compiles cleanly and runs: union members carry $type, Java keywords are escaped, other names are not", () => {
    const main = `package demo;
import java.util.List;
public class Main {
  public static void main(String[] args) {
    Api.Cat cat = new Api.Cat("c1", "Tom", 9);
    Api.Dog dog = new Api.Dog("d1", "Rex", "big", true);
    Api.Pet pet = cat;
    Api.Page<Api.Pet> page = new Api.Page<>(List.of(cat, dog), null, false, 2);
    System.out.println(String.join(" ", cat.$type(), dog.$type(), dog.class_(), String.valueOf(dog.default_()), dog.name(),
      String.valueOf(page.items().size()), Api.Ops.ADOPT_PET, Api.Ops.PETS, Api.Size.LARGE.name(), String.valueOf(pet instanceof Api.Media),
      new Api.Ops.AdoptPetArgs("c1").petId(), new Api.Photo("u", null).$type(), new Api.Adopted("c1", "a@b.c").contact(), new Api.Gone("2026-09-10T00:00:00Z").since()));
  }
}
`;
    const out = compile("pets", { "demo/Api.java": generateJava(loadSchema(PETS).ir, { pkg: "demo", className: "Api" }), "demo/Main.java": main });
    expect(execFileSync("java", ["-cp", out, "demo.Main"], { encoding: "utf8", timeout: JDK_MS }).trim()).toBe("Cat Dog big true Rex 2 adoptPet pets LARGE true c1 Photo a@b.c 2026-09-10T00:00:00Z");
  });

  it.runIf(javac)("components named for Object's methods, and a backslash-u in a description, still compile and run", () => {
    const bs = String.fromCharCode(92);
    const schema = `
"""Paths like C:${bs}users, an escape ${bs}u002a/ that would close this comment, and one ${bs}uZZZZ javac cannot read."""
input Prefs { notify: Boolean wait: Int? hashCode: String? toString: String? clone: Boolean? finalize: Boolean? getClass: String? notifyAll: Boolean? }
entity Account {
  id: ID
  """Set by ${bs}u0041dmin."""
  toString: String
}
query account(prefs: Prefs, wait: Int?): Account`;
    const main = `package edge;
public class Main {
  public static void main(String[] args) {
    Api.Prefs p = new Api.Prefs(true, 5, "h", "t", false, false, "g", true);
    Api.Account a = new Api.Account("a1", "shown");
    System.out.println(String.join(" ", String.valueOf(p.notify_()), String.valueOf(p.wait_()), p.hashCode_(), p.toString_(), p.getClass_(), a.toString_(),
      String.valueOf(new Api.Ops.AccountArgs(p, 3).wait_()), String.valueOf(p.equals(new Api.Prefs(true, 5, "h", "t", false, false, "g", true)))));
  }
}
`;
    const out = compile("edge", { "edge/Api.java": generateJava(loadSchema(schema).ir, { pkg: "edge", className: "Api" }), "edge/Main.java": main });
    expect(execFileSync("java", ["-cp", out, "edge.Main"], { encoding: "utf8", timeout: JDK_MS }).trim()).toBe("true 5 h t g shown 3 true");
  });

  it("guard - names that are not Object's methods, and backslashes not before a u, are written as they are", () => {
    const bs = String.fromCharCode(92);
    const src = generateJava(loadSchema(`"""C:${bs}temp"""\ninput Prefs { notifyMe: Boolean waiting: Int } query q(p: Prefs): Int`).ir);
    expect(src).toContain("public record Prefs(Boolean notifyMe, Integer waiting) {}");
    expect(src).toContain(`/** C:${bs}temp */`);
  });

  it.runIf(javac)("every schema in the repository generates Java that compiles without warnings", () => {
    const fixtures = join(__dirname, "../../../conformance/fixtures/core");
    const schemas: Array<[string, string]> = [["bookstore", bookstoreSchemaText()], ["pets", PETS]];
    for (const f of readdirSync(fixtures).sort()) schemas.push([f, (JSON.parse(readFileSync(join(fixtures, f), "utf8")) as { schema: string }).schema]);
    const sources: Record<string, string> = {};
    schemas.forEach(([, text], i) => (sources[`p${i}/Schema.java`] = generateJava(loadSchema(text).ir, { pkg: `p${i}`, className: "Schema" })));
    compile("all", sources);
    expect(Object.keys(sources)).toHaveLength(schemas.length);
  });
});
