/** TypeScript type generation from the IR: entities, inputs, enums, unions, errors, op signatures. */
import { baseName, type FieldDef, type RayfoldSchemaIR, type TypeDef, type TypeRef } from "./ir.ts";

const SCALARS: Record<string, string> = {
  ID: "string",
  String: "string",
  Int: "number",
  Long: "number | string",
  Float: "number",
  Boolean: "boolean",
  Decimal: "string",
  Instant: "string",
  Date: "string",
  Duration: "number | string",
  Bytes: "string",
  JSON: "unknown",
};

export function generateTypeScript(ir: RayfoldSchemaIR, opts: { header?: boolean } = {}): string {
  const out: string[] = [];
  if (opts.header !== false) out.push("/* Generated by `rayfold gen ts`. Do not edit. */", "");
  const ts = (t: TypeRef): string => {
    const q = t.nullable ? " | null" : "";
    if (t.kind === "list") return `Array<${ts(t.of)}>${q}`;
    if (t.name === "Page" && t.args?.[0]) return `Page<${ts(t.args[0])}>${q}`;
    const def = ir.types[t.name];
    if (def?.kind === "scalar") return (SCALARS[t.name] ?? "string") + q;
    return t.name + q;
  };
  const doc = (d: string | undefined, indent = ""): string[] => (d ? [`${indent}/** ${d.replace(/\*\//g, "* /")} */`] : []);
  const fields = (fs: FieldDef[], indent = "  "): string[] =>
    fs.flatMap((f) => [...doc(f.description, indent), `${indent}${f.name}${f.type.nullable || f.default !== undefined ? "?" : ""}: ${ts(f.type)};`]);

  out.push("export interface Page<T> { items: T[]; cursor: string | null; hasMore: boolean; total?: number | null }");
  out.push("export interface PageArgs { first?: number; after?: string | null; offset?: number | null }");
  out.push("");

  const types = Object.values(ir.types).filter((t) => !t.builtin);
  for (const t of types) {
    out.push(...doc(t.description));
    switch (t.kind) {
      case "entity":
        out.push(`export interface ${t.name} {`, `  $type: "${t.name}";`, ...fields(t.fields), "}");
        break;
      case "object":
      case "input":
      case "event":
      case "error":
        out.push(`export interface ${t.name} {`, ...(t.kind === "object" && !t.interface ? [] : []), ...fields(t.fields), "}");
        break;
      case "enum":
        out.push(`export type ${t.name} = ${t.values.map((v) => JSON.stringify(v.name)).join(" | ")};`);
        break;
      case "union":
        out.push(`export type ${t.name} = ${t.members.join(" | ")};`);
        break;
      case "scalar":
        out.push(`export type ${t.name} = string | number;`);
        break;
    }
    out.push("");
  }

  // Ops
  out.push("export interface Ops {");
  for (const op of Object.values(ir.ops)) {
    const args = op.args.length ? `{ ${op.args.map((a) => `${a.name}${a.type.nullable || a.default !== undefined ? "?" : ""}: ${ts(a.type)}`).join("; ")} }` : "Record<string, never>";
    const errors = op.throws.length ? op.throws.map((e) => `{ type: "${e}"; data: ${e} }`).join(" | ") : "never";
    out.push(...doc(op.description, "  "));
    out.push(`  ${op.name}: { kind: "${op.kind}"; args: ${args}; result: ${ts(op.returns)}; error: ${errors} };`);
  }
  out.push("}");
  out.push("");
  out.push(`export type Queries = { [K in keyof Ops as Ops[K]["kind"] extends "query" ? K : never]: Ops[K] };`);
  out.push(`export type Commands = { [K in keyof Ops as Ops[K]["kind"] extends "command" ? K : never]: Ops[K] };`);
  out.push(`export type Streams = { [K in keyof Ops as Ops[K]["kind"] extends "stream" ? K : never]: Ops[K] };`);
  out.push("");
  const events = types.filter((t): t is Extract<TypeDef, { kind: "event" }> => t.kind === "event");
  out.push(`export interface Events {${events.map((e) => ` ${e.name}: ${e.name};`).join("")} }`);
  out.push("");
  out.push(`export const OP_KINDS = ${JSON.stringify(Object.fromEntries(Object.values(ir.ops).map((o) => [o.name, o.kind])))} as const;`);
  void baseName;
  return out.join("\n") + "\n";
}
