import { execFile } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { bounded } from "../../../e2e/wait.ts";
import { generateKotlin, generateTypeScript, loadSchema } from "./index.ts";

const SHOP = `
"""A book on the shelf."""
entity Book { id: ID """shown on the spine""" title: String pages: Int? tags: [String] price: Money format: Format }
scalar Money
enum Format { PAPER EBOOK }
object Card { title: String }
union Found = Book | Card
input Draft { title: String copies: Int = 1 note: String? }
event BookAdded { id: ID }
query book(id: ID): Book?
query books(page: PageArgs = { first: 20 }): Page<Book>
query search(q: String): [Found]
command addBook(draft: Draft): Book throws Duplicate { title: String } emits BookAdded
stream added: BookAdded
`;

const shop = loadSchema(SHOP);

const KOTLIN_EDGES = String.raw`
input Prefs { notify: Boolean in: Int? }
enum Format { PAPER in EBOOK }
input Filter {
  format: Format = PAPER
  formats: [Format] = [PAPER, in]
  score: Float = 0.5
  min: Float = 1
  big: Float = 1e21
  price: String = "$5 and ${"$"}{x} \f"
  meta: JSON = { "a-b": [1, true] }
  page: PageArgs = { first: 5 }
  prefs: Prefs = { notify: true }
}
"""Closes */ early, /* nests, and keeps \u0041 as text."""
entity Account { id: ID type: String when: String class: String? }
query a(p: Prefs, f: Filter, in: Int = 3, object: Format = EBOOK): Account
`;

const TS = `/* Generated by \`rayfold gen ts\`. Do not edit. */

export interface Page<T> { items: T[]; cursor: string | null; hasMore: boolean; total?: number | null }
export interface PageArgs { first?: number; after?: string | null; offset?: number | null }

/** A book on the shelf. */
export interface Book {
  $type: "Book";
  id: string;
  /** shown on the spine */
  title: string;
  pages?: number | null;
  tags: Array<string>;
  price: string;
  format: Format;
}

export type Money = string | number;

export type Format = "PAPER" | "EBOOK";

export interface Card {
  title: string;
}

export type Found = Book | Card;

export interface Draft {
  title: string;
  copies?: number;
  note?: string | null;
}

export interface BookAdded {
  id: string;
}

export interface Duplicate {
  title: string;
}

export interface Ops {
  book: { kind: "query"; args: { id: string }; result: Book | null; error: never };
  books: { kind: "query"; args: { page?: PageArgs }; result: Page<Book>; error: never };
  search: { kind: "query"; args: { q: string }; result: Array<Found>; error: never };
  addBook: { kind: "command"; args: { draft: Draft }; result: Book; error: { type: "Duplicate"; data: Duplicate } };
  added: { kind: "stream"; args: Record<string, never>; result: BookAdded; error: never };
}

export type Queries = { [K in keyof Ops as Ops[K]["kind"] extends "query" ? K : never]: Ops[K] };
export type Commands = { [K in keyof Ops as Ops[K]["kind"] extends "command" ? K : never]: Ops[K] };
export type Streams = { [K in keyof Ops as Ops[K]["kind"] extends "stream" ? K : never]: Ops[K] };

export interface Events { BookAdded: BookAdded; }

export const OP_KINDS = {"book":"query","books":"query","search":"query","addBook":"command","added":"stream"} as const;
`;

const KOTLIN = `/* Generated by \`rayfold gen kotlin\`. Do not edit. */
package shop.gen

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Page<T>(val items: List<T>, val cursor: String? = null, val hasMore: Boolean, val total: Int? = null)

@Serializable
data class PageArgs(val first: Int = 20, val after: String? = null, val offset: Int? = null)

/** A book on the shelf. */
@Serializable
data class Book(
    @SerialName("\\$type") val type: String = "Book",
    val id: String,
    /** shown on the spine */
    val title: String,
    val pages: Int? = null,
    val tags: List<String>,
    val price: String,
    val format: Format,
)

typealias Money = String

@Serializable
enum class Format { PAPER, EBOOK }

@Serializable
data class Card(
    val title: String,
)

/** union of Book | Card; discriminate on the JSON \`$type\` member */
typealias Found = kotlinx.serialization.json.JsonObject

@Serializable
data class Draft(
    val title: String,
    val copies: Int = 1,
    val note: String? = null,
)

@Serializable
data class BookAdded(
    val id: String,
)

@Serializable
data class Duplicate(
    val title: String,
)

/** Operation names, kinds and argument classes. */
object Ops {
    const val BOOK = "book"
    @Serializable
    data class BookArgs(
        val id: String,
    )
    const val BOOKS = "books"
    @Serializable
    data class BooksArgs(
        val page: PageArgs = PageArgs(first = 20),
    )
    const val SEARCH = "search"
    @Serializable
    data class SearchArgs(
        val q: String,
    )
    const val ADDBOOK = "addBook"
    @Serializable
    data class AddBookArgs(
        val draft: Draft,
    )
    const val ADDED = "added"
}

val OP_KINDS: Map<String, String> = mapOf("book" to "query", "books" to "query", "search" to "query", "addBook" to "command", "added" to "stream")
`;

const work = mkdtempSync(join(tmpdir(), "rayfold-gen-ts-kotlin-"));
afterAll(() => rmSync(work, { recursive: true, force: true }));

describe("generateTypeScript", () => {
  it("prints every kind of type and each operation's signature", () => {
    expect(shop.warnings).toEqual([]);
    expect(generateTypeScript(shop.ir)).toBe(TS);
  });

  it("drops the header on request", () => {
    expect(generateTypeScript(shop.ir, { header: false })).toBe(TS.slice(TS.indexOf("\n\n") + 2));
  });

  it("compiles under tsc --strict, and the types reject what the schema forbids", async () => {
    writeFileSync(join(work, "shop.ts"), generateTypeScript(shop.ir));
    // uses the generated types the way a caller does; the @ts-expect-error lines fail the compile if a type is too loose
    writeFileSync(
      join(work, "use.ts"),
      [
        `import type { Book, Commands, Draft, Events, Found, Ops, Queries, Streams } from "./shop.ts";`,
        `import { OP_KINDS } from "./shop.ts";`,
        `const book: Book = { $type: "Book", id: "b1", title: "Dune", tags: [], price: "9.99", format: "PAPER" };`,
        `const draft: Draft = { title: "Dune" };`,
        `const found: Found[] = [book, { title: "card" }];`,
        `const q: keyof Queries = "search";`,
        `const c: keyof Commands = "addBook";`,
        `const s: keyof Streams = "added";`,
        `const e: Events["BookAdded"] = { id: "b1" };`,
        `const err: Ops["addBook"]["error"] = { type: "Duplicate", data: { title: "Dune" } };`,
        `const kind: "command" = OP_KINDS.addBook;`,
        `// @ts-expect-error format is an enum`,
        `const badFormat: Book["format"] = "HARDBACK";`,
        `// @ts-expect-error addBook is not a query`,
        `const notQuery: keyof Queries = "addBook";`,
        `// @ts-expect-error title is required`,
        `const noTitle: Draft = { copies: 2 };`,
        `export { book, draft, found, q, c, s, e, err, kind, badFormat, notQuery, noTitle };`,
      ].join("\n") + "\n",
    );
    const tsc = join(dirname(createRequire(import.meta.url).resolve("typescript/package.json")), "bin", "tsc");
    const args = [tsc, "--noEmit", "--strict", "--target", "es2022", "--module", "nodenext", "--allowImportingTsExtensions", join(work, "use.ts")];
    const result = await bounded(
      new Promise<{ code: number; out: string }>((resolve) =>
        execFile(process.execPath, args, { cwd: work, timeout: 30_000 }, (e, stdout, stderr) => resolve({ code: e ? ((e as { code?: number }).code ?? -1) : 0, out: stdout + stderr })),
      ),
      "tsc finishes",
      30_000,
    );
    expect(result).toEqual({ code: 0, out: "" });
  }, 40_000);
});

describe("generateKotlin", () => {
  it("prints serializable data classes, argument classes and op kinds in the package asked for", () => {
    expect(generateKotlin(shop.ir, { pkg: "shop.gen" })).toBe(KOTLIN);
  });

  it("defaults the package", () => {
    expect(generateKotlin(shop.ir)).toBe(KOTLIN.replace("package shop.gen", "package dev.rayfold.generated"));
  });

  // The file this generates is compiled by the Kotlin build (rayfold-core's tests) and used by GeneratedKotlinTest.kt,
  // which is what proves the output compiles: a keyword field, a field named type, enum, Float and JSON defaults, a $
  // in a string and comment text that would close or nest a comment. Regenerate it with UPDATE_GOLDEN=1.
  it("writes Kotlin that compiles for names and defaults Kotlin reads differently (the checked-in file the Kotlin build compiles)", () => {
    const golden = new URL("../../../kotlin/rayfold-core/src/test/kotlin/dev/rayfold/generated/edges/Edges.kt", import.meta.url);
    const text = generateKotlin(loadSchema(KOTLIN_EDGES).ir, { pkg: "dev.rayfold.generated.edges" });
    if (process.env["UPDATE_GOLDEN"]) writeFileSync(golden, text);
    expect(text).toBe(readFileSync(golden, "utf8"));
    expect(text).toContain('    @SerialName("\\$type") val type_: String = "Account",\n    val id: String,\n    val type: String,\n    val `when`: String,');
    expect(text).toContain("    val format: Format = Format.PAPER,\n    val formats: List<Format> = listOf(Format.PAPER, Format.`in`),");
    expect(text).toContain("    val min: Double = 1.0,\n    val big: Double = 1e+21,");
    expect(text).toContain('    val price: String = "\\$5 and \\${x} \\u000c",');
    expect(text).toContain('    val meta: kotlinx.serialization.json.JsonElement = kotlinx.serialization.json.Json.parseToJsonElement("{\\"a-b\\":[1,true]}"),');
    expect(text).toContain("/** Closes * / early, / * nests, and keeps \\u0041 as text. */");
  });

  it("guard - a name that is not a Kotlin keyword and an entity with no type field are written as before", () => {
    const text = generateKotlin(loadSchema(`entity A { id: ID when2: Int } query a: A`).ir);
    expect(text).toContain('    @SerialName("\\$type") val type: String = "A",\n    val id: String,\n    val when2: Int,');
  });

  it("an object with no fields is a plain class, not an empty data class", () => {
    const { ir } = loadSchema(`object Empty {} query e: Empty`);
    expect(generateKotlin(ir).split("\n").slice(12, 15)).toEqual(["@Serializable", "class Empty", ""]);
  });
});
