/** Kotlin data-class generation from the IR (`rayfold gen kotlin`): kotlinx.serialization models for entities, inputs, enums, errors, events and op signatures. */
import type { FieldDef, RayfoldSchemaIR, TypeDef, TypeRef } from "./ir.ts";

const SCALARS: Record<string, string> = {
  ID: "String",
  String: "String",
  Int: "Int",
  Long: "Long",
  Float: "Double",
  Boolean: "Boolean",
  Decimal: "String",
  Instant: "String",
  Date: "String",
  Duration: "String",
  Bytes: "String",
  JSON: "kotlinx.serialization.json.JsonElement",
};

export function generateKotlin(ir: RayfoldSchemaIR, opts: { pkg?: string } = {}): string {
  const pkg = opts.pkg ?? "dev.rayfold.generated";
  const out: string[] = [`/* Generated by \`rayfold gen kotlin\`. Do not edit. */`, `package ${pkg}`, "", "import kotlinx.serialization.SerialName", "import kotlinx.serialization.Serializable", ""];
  const kt = (t: TypeRef): string => {
    const q = t.nullable ? "?" : "";
    if (t.kind === "list") return `List<${kt(t.of)}>${q}`;
    if (t.name === "Page" && t.args?.[0]) return `Page<${kt(t.args[0])}>${q}`;
    const def = ir.types[t.name];
    if (def?.kind === "scalar") return (SCALARS[t.name] ?? "String") + q;
    return t.name + q;
  };
  const doc = (d: string | undefined, indent = ""): string[] => (d ? [`${indent}/** ${d.replace(/\*\//g, "* /")} */`] : []);
  const props = (fs: FieldDef[], indent = "    "): string =>
    fs.map((f) => [...doc(f.description, indent), `${indent}val ${f.name}: ${kt(f.type)}${f.type.nullable ? " = null" : f.default !== undefined ? ` = ${kotlinLiteral(f.default)}` : ""},`].join("\n")).join("\n");

  out.push("@Serializable", "data class Page<T>(val items: List<T>, val cursor: String? = null, val hasMore: Boolean, val total: Int? = null)", "");
  out.push("@Serializable", "data class PageArgs(val first: Int = 20, val after: String? = null, val offset: Int? = null)", "");

  for (const t of Object.values(ir.types).filter((x) => !x.builtin)) {
    out.push(...doc(t.description));
    switch (t.kind) {
      case "entity":
        out.push("@Serializable", `data class ${t.name}(`, `    @SerialName("\\$type") val type: String = "${t.name}",`, props(t.fields), ")");
        break;
      case "object":
      case "input":
      case "error":
      case "event":
        if (t.fields.length === 0) out.push("@Serializable", `class ${t.name}`);
        else out.push("@Serializable", `data class ${t.name}(`, props(t.fields), ")");
        break;
      case "enum":
        out.push("@Serializable", `enum class ${t.name} { ${t.values.map((v) => v.name).join(", ")} }`);
        break;
      case "union":
        out.push(`/** union of ${t.members.join(" | ")}; discriminate on the JSON \`$type\` member */`, `typealias ${t.name} = kotlinx.serialization.json.JsonObject`);
        break;
      case "scalar":
        out.push(`typealias ${t.name} = String`);
        break;
    }
    out.push("");
  }

  out.push("/** Operation names, kinds and argument classes. */", "object Ops {");
  for (const op of Object.values(ir.ops)) {
    const argsClass = `${cap(op.name)}Args`;
    out.push(`    const val ${op.name.toUpperCase()} = "${op.name}"`);
    if (op.args.length) {
      out.push("    @Serializable", `    data class ${argsClass}(`);
      for (const a of op.args) out.push(`        val ${a.name}: ${kt(a.type)}${a.type.nullable ? " = null" : a.default !== undefined ? ` = ${kotlinLiteral(a.default)}` : ""},`);
      out.push("    )");
    }
  }
  out.push("}", "");
  out.push(`val OP_KINDS: Map<String, String> = mapOf(${Object.values(ir.ops).map((o) => `"${o.name}" to "${o.kind}"`).join(", ")})`);
  return out.join("\n") + "\n";
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function kotlinLiteral(v: unknown): string {
  if (v === null) return "null";
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `listOf(${v.map(kotlinLiteral).join(", ")})`;
  if (typeof v === "object") {
    const o = v as Record<string, unknown>;
    if ("first" in o) return `PageArgs(${Object.entries(o).map(([k, x]) => `${k} = ${kotlinLiteral(x)}`).join(", ")})`;
    return `TODO("object default")`;
  }
  return "null";
}

export type { TypeDef };
