/** Kotlin data-class generation from the IR (`rayfold gen kotlin`): kotlinx.serialization models for entities, inputs, enums, errors, events and op signatures. */
import type { FieldDef, JsonValue, RayfoldSchemaIR, TypeDef, TypeRef } from "./ir.ts";

const SCALARS: Record<string, string> = {
  ID: "String",
  String: "String",
  Int: "Int",
  Long: "Long",
  Float: "Double",
  Boolean: "Boolean",
  Decimal: "String",
  Instant: "String",
  Date: "String",
  Duration: "String",
  Bytes: "String",
  JSON: "kotlinx.serialization.json.JsonElement",
};

/** Kotlin's hard keywords: a property, parameter or constant with one of these names must be written in backticks. */
const KOTLIN_KEYWORDS = new Set([
  "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in", "interface", "is", "null", "object",
  "package", "return", "super", "this", "throw", "true", "try", "typealias", "typeof", "val", "var", "when", "while",
]);

/** A schema name as a Kotlin identifier: keywords go in backticks (`in` is \`in\`), which keeps the JSON name as it is. */
const ident = (name: string): string => (KOTLIN_KEYWORDS.has(name) ? `\`${name}\`` : name);

export function generateKotlin(ir: RayfoldSchemaIR, opts: { pkg?: string } = {}): string {
  const pkg = opts.pkg ?? "dev.rayfold.generated";
  const out: string[] = [`/* Generated by \`rayfold gen kotlin\`. Do not edit. */`, `package ${pkg}`, "", "import kotlinx.serialization.SerialName", "import kotlinx.serialization.Serializable", ""];
  const kt = (t: TypeRef): string => {
    const q = t.nullable ? "?" : "";
    if (t.kind === "list") return `List<${kt(t.of)}>${q}`;
    if (t.name === "Page" && t.args?.[0]) return `Page<${kt(t.args[0])}>${q}`;
    const def = ir.types[t.name];
    if (def?.kind === "scalar") return (SCALARS[t.name] ?? "String") + q;
    return ident(t.name) + q;
  };
  /** A default as a Kotlin expression of the declared type: an enum constant, a Double, an input's constructor. */
  const literal = (v: JsonValue, t: TypeRef): string => {
    if (v === null) return "null";
    if (t.kind === "list") return `listOf(${(Array.isArray(v) ? v : [v]).map((x) => literal(x, t.of)).join(", ")})`;
    const def = ir.types[t.name];
    if (def?.kind === "enum" && typeof v === "string") return `${ident(t.name)}.${ident(v)}`;
    if (def && "fields" in def && typeof v === "object" && !Array.isArray(v)) {
      const fields = def.fields;
      return `${ident(t.name)}(${Object.entries(v)
        .map(([k, x]) => {
          const f = fields.find((ff) => ff.name === k);
          return `${ident(k)} = ${f ? literal(x, f.type) : kotlinString(JSON.stringify(x))}`;
        })
        .join(", ")})`;
    }
    switch (kt({ ...t, nullable: false })) {
      case "Double":
        return typeof v === "number" ? kotlinDouble(v) : kotlinString(String(v));
      case "Int":
      case "Long":
      case "Boolean":
        return typeof v === "string" ? kotlinString(v) : String(v);
      case "kotlinx.serialization.json.JsonElement":
        return `kotlinx.serialization.json.Json.parseToJsonElement(${kotlinString(JSON.stringify(v))})`;
      default:
        return kotlinString(typeof v === "string" ? v : JSON.stringify(v));
    }
  };
  // Kotlin comments nest, so an opening /* in the text would swallow the closing */ as well as a closing one would end it early
  const doc = (d: string | undefined, indent = ""): string[] => (d ? [`${indent}/** ${d.replace(/\*\//g, "* /").replace(/\/\*/g, "/ *")} */`] : []);
  const prop = (f: { name: string; type: TypeRef; default?: JsonValue }): string =>
    `val ${ident(f.name)}: ${kt(f.type)}${f.type.nullable ? " = null" : f.default !== undefined ? ` = ${literal(f.default, f.type)}` : ""},`;
  const props = (fs: FieldDef[], indent = "    "): string => fs.map((f) => [...doc(f.description, indent), `${indent}${prop(f)}`].join("\n")).join("\n");

  out.push("@Serializable", "data class Page<T>(val items: List<T>, val cursor: String? = null, val hasMore: Boolean, val total: Int? = null)", "");
  out.push("@Serializable", "data class PageArgs(val first: Int = 20, val after: String? = null, val offset: Int? = null)", "");

  for (const t of Object.values(ir.types).filter((x) => !x.builtin)) {
    out.push(...doc(t.description));
    switch (t.kind) {
      case "entity": {
        // the discriminator takes `type` unless a field of the schema already has that name
        let discriminator = "type";
        while (t.fields.some((f) => f.name === discriminator)) discriminator += "_";
        out.push("@Serializable", `data class ${ident(t.name)}(`, `    @SerialName("\\$type") val ${discriminator}: String = "${t.name}",`, props(t.fields), ")");
        break;
      }
      case "object":
      case "input":
      case "error":
      case "event":
        if (t.fields.length === 0) out.push("@Serializable", `class ${ident(t.name)}`);
        else out.push("@Serializable", `data class ${ident(t.name)}(`, props(t.fields), ")");
        break;
      case "enum":
        out.push("@Serializable", `enum class ${ident(t.name)} { ${t.values.map((v) => ident(v.name)).join(", ")} }`);
        break;
      case "union":
        out.push(`/** union of ${t.members.join(" | ")}; discriminate on the JSON \`$type\` member */`, `typealias ${ident(t.name)} = kotlinx.serialization.json.JsonObject`);
        break;
      case "scalar":
        out.push(`typealias ${ident(t.name)} = String`);
        break;
    }
    out.push("");
  }

  out.push("/** Operation names, kinds and argument classes. */", "object Ops {");
  for (const op of Object.values(ir.ops)) {
    const argsClass = `${cap(op.name)}Args`;
    out.push(`    const val ${op.name.toUpperCase()} = "${op.name}"`);
    if (op.args.length) {
      out.push("    @Serializable", `    data class ${argsClass}(`);
      for (const a of op.args) out.push(`        ${prop(a)}`);
      out.push("    )");
    }
  }
  out.push("}", "");
  out.push(`val OP_KINDS: Map<String, String> = mapOf(${Object.values(ir.ops).map((o) => `"${o.name}" to "${o.kind}"`).join(", ")})`);
  return out.join("\n") + "\n";
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/** A Kotlin string literal: `$` is escaped so it never starts a template, and no escape Kotlin lacks (\\f) is used. */
function kotlinString(s: string): string {
  let out = '"';
  for (const ch of s) {
    const c = ch.codePointAt(0)!;
    if (ch === '"' || ch === "\\" || ch === "$") out += `\\${ch}`;
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (c < 0x20 || (c >= 0xd800 && c <= 0xdfff)) out += `\\u${c.toString(16).padStart(4, "0")}`;
    else out += ch;
  }
  return out + '"';
}

/** A Double literal: 1 is 1.0, since Kotlin does not widen an Int literal to Double. */
function kotlinDouble(v: number): string {
  const text = String(v);
  return /[.eE]/.test(text) ? text : `${text}.0`;
}

export type { TypeDef };
