package dev.rayfold.core

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.put
import java.io.ByteArrayOutputStream
import java.io.InputStream
import java.math.BigDecimal
import java.math.RoundingMode
import java.net.Socket
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger

/**
 * Outputs of the TypeScript reference, generated by scratchpad `oracle.ts` with the TS runtime and checked in under
 * `src/test/resources/oracle`: IRs of the schemas the TS tests use, and the OpenAPI/MCP documents TS makes from them.
 * Stateless: every call reads the resource again.
 */
object Oracle {
    fun text(name: String): String = (Oracle::class.java.getResource("/oracle/$name") ?: error("missing oracle resource $name")).readText()
    fun json(name: String): JsonElement = Json.parseToJsonElement(text(name))
    fun ir(name: String): RayfoldSchemaIR = RayfoldSchemaIR.parse(text(name))
}

/** The viewer the TS tests derive from Authorization: admin, a customer named by the token, or nobody. */
fun viewerOf(authorization: String?): JsonElement = when {
    authorization == "Bearer admin" -> obj("""{"id":"u9","role":"admin"}""")
    authorization != null && authorization.startsWith("Bearer ") -> buildJsonObject { put("id", authorization.removePrefix("Bearer ")); put("role", "customer") }
    else -> JsonNull
}

/** examples/bookstore-ts/src/data.ts: the seed, rebuilt for every store. Tables are concurrent because transports run on worker threads. */
class BookstoreStore {
    val authors = ConcurrentHashMap<String, JsonObject>()
    val books = ConcurrentHashMap<String, JsonObject>()
    val reviews = ConcurrentHashMap<String, JsonObject>()
    val orders = ConcurrentHashMap<String, JsonObject>()
    val nextId = AtomicInteger(1)
    /** Loader invocations, for N+1 and "nothing ran" assertions. */
    val calls = ConcurrentHashMap<String, Int>()

    fun count(k: String) { calls.merge(k, 1, Int::plus) }

    init {
        for (a in listOf(
            """{"id":"a1","name":"Ursula K. Le Guin","bio":"American author of speculative fiction."}""",
            """{"id":"a2","name":"Italo Calvino","bio":null}""",
            """{"id":"a3","name":"Octavia E. Butler","bio":"Science fiction author from Pasadena."}""",
        )) obj(a).let { authors[it.s("id")] = it }
        for (b in listOf(
            """{"id":"b1","title":"The Dispossessed","format":"PAPERBACK","price":"12.99","stock":5,"authorId":"a1","costPrice":"6.10","ownerId":"u1"}""",
            """{"id":"b2","title":"Invisible Cities","format":"HARDCOVER","price":"19.50","stock":2,"authorId":"a2","costPrice":"9.00","ownerId":"u2"}""",
            """{"id":"b3","title":"Kindred","format":"EBOOK","price":"8.00","stock":100,"authorId":"a3","costPrice":"1.00","ownerId":"u1"}""",
            """{"id":"b4","title":"A Wizard of Earthsea","format":"PAPERBACK","price":"9.99","stock":0,"authorId":"a1","costPrice":"4.50","ownerId":"u1"}""",
        )) obj(b).let { books[it.s("id")] = it }
        for (r in listOf(
            """{"id":"r1","rating":5,"body":"Ambiguous utopia, unambiguous masterpiece.","bookId":"b1","reviewerId":"u2","version":1}""",
            """{"id":"r2","rating":4,"body":"Dreamlike.","bookId":"b2","reviewerId":"u1","version":1}""",
            """{"id":"r3","rating":5,"body":"Devastating.","bookId":"b3","reviewerId":"u2","version":1}""",
            """{"id":"r4","rating":3,"body":"Slow start.","bookId":"b1","reviewerId":"u3","version":1}""",
        )) obj(r).let { reviews[it.s("id")] = it }
    }

    fun stock(bookId: String): Int? = books[bookId]?.i("stock")
}

internal fun JsonObject.s(k: String): String = (this[k] as? JsonPrimitive)?.contentOrNull ?: error("row has no $k: $this")
internal fun JsonObject.i(k: String): Int = (this[k] as? JsonPrimitive)?.intOrNull ?: error("row has no integer $k: $this")
private fun JsonObject.with(vararg kv: Pair<String, JsonElement>): JsonObject = JsonObject(this + kv)

/** A fresh bookstore: the TS example's schema (as the TS runtime compiled it) over a freshly seeded store. */
class Bookstore(options: BatchOptions = BatchOptions(), instrumentation: Instrumentation = Instrumentation.NONE) {
    val store = BookstoreStore()
    val server = RayfoldServer(Oracle.ir("bookstore.ir.json"), bookstoreResolvers(store), options, instrumentation = instrumentation)
}

/** examples/bookstore-ts/src/resolvers.ts, statement for statement. Every entity-field loader is batch: one call per level. */
fun bookstoreResolvers(s: BookstoreStore): Resolvers {
    fun sorted(rows: Collection<JsonObject>) = rows.sortedBy { it.s("id") }
    fun page(rows: List<JsonObject>, p: JsonObject?): JsonObject {
        val first = (p?.get("first") as? JsonPrimitive)?.intOrNull ?: 20
        val after = (p?.get("after") as? JsonPrimitive)?.contentOrNull
        val offset = (p?.get("offset") as? JsonPrimitive)?.intOrNull
        var start = 0
        if (!after.isNullOrEmpty()) {
            val idx = rows.indexOfFirst { it.s("id") == after }
            start = if (idx < 0) rows.size else idx + 1
        } else if (offset != null && offset != 0) start = offset
        val items = rows.drop(start).take(first)
        return buildJsonObject {
            put("items", JsonArray(items))
            put("cursor", items.lastOrNull()?.get("id") ?: JsonNull)
            put("hasMore", start + first < rows.size)
            put("total", rows.size)
        }
    }
    fun viewer(ctx: RayfoldContext) = ctx.viewer as? JsonObject ?: JsonObject(emptyMap())
    fun money(n: BigDecimal): String = n.setScale(2, RoundingMode.HALF_UP).toPlainString()
    fun text(o: JsonObject?, k: String) = (o?.get(k) as? JsonPrimitive)?.contentOrNull
    fun notFound(what: String): Nothing = throw RayfoldException(Code.NOT_FOUND, "$what not found")
    fun mayChange(v: JsonObject, ownerId: String) = text(v, "id") == ownerId || text(v, "role") == "admin"

    val queries = mapOf<String, RootResolver>(
        "books" to { args, _ ->
            s.count("Query.books")
            var rows = sorted(s.books.values)
            val f = args["filter"] as? JsonObject
            text(f, "titleContains")?.takeIf { it.isNotEmpty() }?.let { t -> rows = rows.filter { it.s("title").lowercase().contains(t.lowercase()) } }
            text(f, "format")?.takeIf { it.isNotEmpty() }?.let { t -> rows = rows.filter { it.s("format") == t } }
            text(f, "authorId")?.takeIf { it.isNotEmpty() }?.let { t -> rows = rows.filter { it.s("authorId") == t } }
            text(f, "maxPrice")?.takeIf { it.isNotEmpty() }?.let { t -> rows = rows.filter { BigDecimal(it.s("price")) <= BigDecimal(t) } }
            page(rows, args["page"] as? JsonObject)
        },
        "book" to { args, _ -> s.count("Query.book"); s.books[args.s("id")] ?: JsonNull },
        "author" to { args, _ -> s.count("Query.author"); s.authors[args.s("id")] ?: JsonNull },
        "order" to { args, _ -> s.count("Query.order"); s.orders[args.s("id")] ?: JsonNull },
        "review" to { args, _ -> s.count("Query.review"); s.reviews[args.s("id")] ?: JsonNull },
        "myOrders" to { args, ctx ->
            s.count("Query.myOrders")
            val v = viewer(ctx)
            page(sorted(s.orders.values.filter { it.s("customerId") == text(v, "id") }), args["page"] as? JsonObject)
        },
    )

    val commands = mapOf<String, suspend (JsonObject, RayfoldContext) -> Any?>(
        "placeOrder" to { args, ctx ->
            s.count("Command.placeOrder")
            val v = viewer(ctx)
            val lines = ((args["input"] as? JsonObject)?.get("lines") as? JsonArray)?.map { it as JsonObject } ?: emptyList()
            val items = mutableListOf<JsonObject>()
            var total = BigDecimal.ZERO
            for (line in lines) {
                val b = s.books[line.s("bookId")] ?: notFound("Book ${line.s("bookId")}")
                val qty = line.i("qty")
                if (b.i("stock") < qty) throw RayfoldException.domain("OutOfStock", buildJsonObject { put("bookId", b.s("id")); put("available", b.i("stock")) }, "Only ${b.i("stock")} of ${b.s("title")} left")
                items.add(buildJsonObject { put("bookId", b.s("id")); put("qty", qty); put("unitPrice", b.s("price")) })
                total += BigDecimal(b.s("price")) * BigDecimal(qty)
            }
            if (total > BigDecimal(500)) throw RayfoldException.domain("PaymentDeclined", obj("""{"reason":"limit"}"""), "Order exceeds the card limit")
            val id = "o${if (ctx.simulate) s.nextId.get() else s.nextId.getAndIncrement()}"
            val order = buildJsonObject {
                put("id", id); put("status", "PLACED"); put("customerId", text(v, "id")); put("items", JsonArray(items)); put("total", money(total))
            }
            val patch = mutableListOf<JsonObject>()
            val emit = mutableListOf("OrderPlaced" to buildJsonObject { put("orderId", id); put("customerId", text(v, "id")) })
            // a simulated order reports the same effects as a real one; only the writes are skipped
            if (!ctx.simulate) s.orders[id] = order
            for (it in items) {
                val b = s.books.getValue(it.s("bookId"))
                val stock = b.i("stock") - it.i("qty")
                if (!ctx.simulate) s.books[b.s("id")] = b.with("stock" to JsonPrimitive(stock))
                patch.add(buildJsonObject { put("set", "Book:${b.s("id")}"); put("value", buildJsonObject { put("stock", stock) }) })
                emit.add("StockChanged" to buildJsonObject { put("bookId", b.s("id")); put("stock", stock) })
            }
            CommandResult(order, patch, emit)
        },
        "cancelOrder" to { args, ctx ->
            s.count("Command.cancelOrder")
            val v = viewer(ctx)
            val o = s.orders[args.s("id")]?.takeIf { mayChange(v, it.s("customerId")) } ?: notFound("Order ${args.s("id")}")
            if (o.s("status") != "PLACED") throw RayfoldException.domain("NotCancellable", buildJsonObject { put("status", o.s("status")) }, "Order is ${o.s("status")}")
            val cancelled = o.with("status" to JsonPrimitive("CANCELLED"))
            if (ctx.simulate) cancelled
            else {
                s.orders[o.s("id")] = cancelled
                val items = (o["items"] as JsonArray).map { it as JsonObject }
                for (it in items) s.books.computeIfPresent(it.s("bookId")) { _, b -> b.with("stock" to JsonPrimitive(b.i("stock") + it.i("qty"))) }
                CommandResult(cancelled, items.map { buildJsonObject { put("set", "Book:${it.s("bookId")}"); put("value", buildJsonObject { put("stock", s.stock(it.s("bookId"))) }) } })
            }
        },
        "addReview" to { args, ctx ->
            s.count("Command.addReview")
            val v = viewer(ctx)
            val input = args["input"] as JsonObject
            if (!s.books.containsKey(input.s("bookId"))) notFound("Book ${input.s("bookId")}")
            val rating = input.i("rating")
            if (rating < 1 || rating > 5) throw RayfoldException(Code.INVALID_ARGUMENT, "rating must be 1..5")
            val r = buildJsonObject {
                put("id", "r${if (ctx.simulate) s.nextId.get() else s.nextId.getAndIncrement()}"); put("rating", rating); put("body", input.s("body"))
                put("bookId", input.s("bookId")); put("reviewerId", text(v, "id")); put("version", 1)
            }
            if (!ctx.simulate) s.reviews[r.s("id")] = r
            CommandResult(r, listOf(obj("""{"invOp":["books"]}""")))
        },
        "payOrder" to { args, ctx ->
            s.count("Command.payOrder")
            val v = viewer(ctx)
            val o = s.orders[args.s("id")]?.takeIf { mayChange(v, it.s("customerId")) } ?: notFound("Order ${args.s("id")}")
            if (o.s("status") != "PLACED") throw RayfoldException.domain("NotPayable", buildJsonObject { put("status", o.s("status")) }, "Order is ${o.s("status")}")
            if (BigDecimal(o.s("total")) > BigDecimal(400)) throw RayfoldException.domain("PaymentDeclined", obj("""{"reason":"limit"}"""), "Payment exceeds the card limit")
            val paid = o.with("status" to JsonPrimitive("PAID"))
            if (!ctx.simulate) s.orders[o.s("id")] = paid
            paid
        },
        "editReview" to { args, ctx ->
            s.count("Command.editReview")
            val v = viewer(ctx)
            val r = s.reviews[args.s("id")] ?: notFound("Review ${args.s("id")}")
            if (!mayChange(v, r.s("reviewerId"))) throw RayfoldException(Code.PERMISSION_DENIED, "Only the author of a review can edit it")
            ctx.checkVersion("Review:${r.s("id")}", r["version"], r)
            val input = args["input"] as JsonObject
            val next = r.with("rating" to JsonPrimitive(input.i("rating")), "body" to JsonPrimitive(input.s("body")), "version" to JsonPrimitive(r.i("version") + 1))
            if (!ctx.simulate) s.reviews[r.s("id")] = next
            next
        },
        "updateBook" to { args, ctx ->
            s.count("Command.updateBook")
            val b = s.books[args.s("id")] ?: notFound("Book ${args.s("id")}")
            val patch = args["patch"] as JsonObject
            for ((k, x) in patch) if (x is JsonNull) throw RayfoldException(Code.INVALID_ARGUMENT, "updateBook().patch.$k: cannot be cleared")
            val next = JsonObject(b + patch)
            if (!ctx.simulate) s.books[b.s("id")] = next
            next
        },
        "deleteReview" to { args, ctx ->
            s.count("Command.deleteReview")
            val v = viewer(ctx)
            val r = s.reviews[args.s("id")] ?: notFound("Review ${args.s("id")}")
            if (!mayChange(v, r.s("reviewerId"))) throw RayfoldException(Code.PERMISSION_DENIED, "Only the author of a review can delete it")
            if (!ctx.simulate) s.reviews.remove(r.s("id"))
            CommandResult(r, listOf(buildJsonObject { put("del", "Review:${r.s("id")}") }))
        },
        "restock" to { args, ctx ->
            s.count("Command.restock")
            val b = s.books[args.s("bookId")] ?: notFound("Book ${args.s("bookId")}")
            val next = b.with("stock" to JsonPrimitive(b.i("stock") + args.i("qty")))
            if (ctx.simulate) next
            else {
                s.books[b.s("id")] = next
                CommandResult(next, emit = listOf("StockChanged" to buildJsonObject { put("bookId", b.s("id")); put("stock", next.i("stock")) }))
            }
        },
    )

    val fields = mapOf<String, Map<String, FieldLoader>>(
        "Book" to mapOf(
            "author" to { parents, _, _ -> s.count("Book.author"); parents.map { s.authors[it.s("authorId")] } },
            "reviews" to { parents, args, _ ->
                s.count("Book.reviews")
                val all = sorted(s.reviews.values)
                parents.map { b -> page(all.filter { it.s("bookId") == b.s("id") }, args["page"] as? JsonObject) }
            },
        ),
        "Author" to mapOf(
            "books" to { parents, args, _ ->
                s.count("Author.books")
                val all = sorted(s.books.values)
                parents.map { a -> page(all.filter { it.s("authorId") == a.s("id") }, args["page"] as? JsonObject) }
            },
        ),
        "Review" to mapOf("book" to { parents, _, _ -> s.count("Review.book"); parents.map { s.books[it.s("bookId")] } }),
        "OrderItem" to mapOf("book" to { parents, _, _ -> s.count("OrderItem.book"); parents.map { s.books[it.s("bookId")] } }),
    )
    return Resolvers(queries = queries, commands = commands, fields = fields)
}

/** The seeded order o1 the TS tests insert: two copies of Kindred. */
val ORDER_O1_ROW: JsonObject = obj("""{"id":"o1","status":"PLACED","customerId":"u1","items":[{"bookId":"b3","qty":2,"unitPrice":"8.00"}],"total":"16.00"}""")

/** A raw HTTP/1.1 exchange, for headers the JDK client will not send (Host) and for requests it would rewrite. */
class RawResponse(val status: Int, val head: String, val body: String) {
    fun header(name: String): String? = head.split("\r\n").drop(1).firstOrNull { it.substringBefore(':').trim().equals(name, ignoreCase = true) }?.substringAfter(':')?.trim()
}

/** Sends [request] as is (it should say `Connection: close`) and reads until the server closes; bounded by a 5 s socket timeout. */
fun rawHttp(port: Int, request: String): RawResponse = Socket("127.0.0.1", port).use { s ->
    s.soTimeout = 5000
    s.getOutputStream().write(request.toByteArray())
    s.getOutputStream().flush()
    val text = readAll(s.getInputStream()).toString(Charsets.UTF_8)
    val end = text.indexOf("\r\n\r\n")
    val head = if (end < 0) text else text.substring(0, end)
    RawResponse(head.substringAfter(' ').substringBefore(' ').toIntOrNull() ?: 0, head, if (end < 0) "" else text.substring(end + 4))
}

fun readAll(input: InputStream): ByteArray {
    val out = ByteArrayOutputStream()
    val buf = ByteArray(8192)
    while (true) {
        val n = try { input.read(buf) } catch (e: java.net.SocketException) { -1 }
        if (n < 0) return out.toByteArray()
        out.write(buf, 0, n)
    }
}
