/* Generated by `rayfold gen ts`. Do not edit. */

export interface Page<T> { items: T[]; cursor: string | null; hasMore: boolean; total?: number | null }
export interface PageArgs { first?: number; after?: string | null; offset?: number | null }

export interface Author {
  $type: "Author";
  id: string;
  name: string;
  bio?: string | null;
  books: Page<Book>;
}

export interface Book {
  $type: "Book";
  id: string;
  title: string;
  format: Format;
  /** Unit price in the store currency. */
  price: string;
  stock: number;
  author: Author;
  reviews: Page<Review>;
  /** Only the owner (or an admin) can see the cost price. */
  costPrice?: string | null;
  ownerId: string;
}

export interface Review {
  $type: "Review";
  id: string;
  rating: number;
  body: string;
  book: Book;
  reviewerId: string;
  /** Bumped on every edit; send it back as ifVersion (or If-Match) to avoid lost updates. */
  version: number;
}

export interface Order {
  $type: "Order";
  id: string;
  status: OrderStatus;
  customerId: string;
  items: Array<OrderItem>;
  total: string;
}

export interface OrderItem {
  book: Book;
  qty: number;
  unitPrice: string;
}

export type Format = "HARDCOVER" | "PAPERBACK" | "EBOOK";

export type OrderStatus = "PLACED" | "PAID" | "SHIPPED" | "CANCELLED";

export interface BookFilter {
  titleContains?: string | null;
  format?: Format | null;
  authorId?: string | null;
  maxPrice?: string | null;
}

export interface OrderLine {
  bookId: string;
  qty?: number;
}

export interface OrderInput {
  lines: Array<OrderLine>;
}

export interface ReviewInput {
  bookId: string;
  rating: number;
  body: string;
}

export interface ReviewEdit {
  rating: number;
  body: string;
}

/** Partial update: absent fields are left unchanged. */
export interface BookPatch {
  title?: string | null;
  price?: string | null;
  stock?: number | null;
}

export interface OutOfStock {
  bookId: string;
  available: number;
}

export interface PaymentDeclined {
  reason: string;
}

export interface OrderPlaced {
  orderId: string;
  customerId: string;
}

export interface StockChanged {
  bookId: string;
  stock: number;
}

export interface NotPayable {
  status: OrderStatus;
}

export interface NotCancellable {
  status: OrderStatus;
}

export interface Ops {
  /** List books, newest first. */
  books: { kind: "query"; args: { filter?: BookFilter | null; page?: PageArgs }; result: Page<Book>; error: never };
  book: { kind: "query"; args: { id: string }; result: Book | null; error: never };
  author: { kind: "query"; args: { id: string }; result: Author | null; error: never };
  review: { kind: "query"; args: { id: string }; result: Review | null; error: never };
  order: { kind: "query"; args: { id: string }; result: Order | null; error: never };
  myOrders: { kind: "query"; args: { page?: PageArgs }; result: Page<Order>; error: never };
  /** Place an order. Fails atomically if any line is out of stock. */
  placeOrder: { kind: "command"; args: { input: OrderInput }; result: Order; error: { type: "OutOfStock"; data: OutOfStock } | { type: "PaymentDeclined"; data: PaymentDeclined } };
  /** Pay for a placed order. */
  payOrder: { kind: "command"; args: { id: string }; result: Order; error: { type: "PaymentDeclined"; data: PaymentDeclined } | { type: "NotPayable"; data: NotPayable } };
  cancelOrder: { kind: "command"; args: { id: string }; result: Order; error: { type: "NotCancellable"; data: NotCancellable } };
  addReview: { kind: "command"; args: { input: ReviewInput }; result: Review; error: never };
  /** Replace a review's rating and text. Only its author (or an admin) may edit it. */
  editReview: { kind: "command"; args: { id: string; input: ReviewEdit }; result: Review; error: never };
  /** Change some fields of a book; fields not sent are left as they are. */
  updateBook: { kind: "command"; args: { id: string; patch: BookPatch }; result: Book; error: never };
  /** Delete a review. Only its author (or an admin) may delete it. */
  deleteReview: { kind: "command"; args: { id: string }; result: Review; error: never };
  restock: { kind: "command"; args: { bookId: string; qty: number }; result: Book; error: never };
  stockUpdates: { kind: "stream"; args: { bookIds: Array<string> }; result: StockChanged; error: never };
}

export type Queries = { [K in keyof Ops as Ops[K]["kind"] extends "query" ? K : never]: Ops[K] };
export type Commands = { [K in keyof Ops as Ops[K]["kind"] extends "command" ? K : never]: Ops[K] };
export type Streams = { [K in keyof Ops as Ops[K]["kind"] extends "stream" ? K : never]: Ops[K] };

export interface Events { OrderPlaced: OrderPlaced; StockChanged: StockChanged; }

export const OP_KINDS = {"books":"query","book":"query","author":"query","review":"query","order":"query","myOrders":"query","placeOrder":"command","payOrder":"command","cancelOrder":"command","addReview":"command","editReview":"command","updateBook":"command","deleteReview":"command","restock":"command","stockUpdates":"stream"} as const;
